### ISSUE TITLE
Cancel traversion; get connected vertices/edges

### ISSUE THREAD

**Issue by strarsis** [datastructures-js/graph#22]
@eyas-ranjous, @olegpetroveth:
For a particular application I just want the vertices directly connected to a given vertex (undirected cyclical graph).
The currently available traversal functions `traverseDfs` and `traverseBfs` [don't support](https://github.com/datastructures-js/graph/blob/877f7e409186fd14721a392e911fe703d6c80947/src/directedGraph.js#L186) [cancelling the traversion](https://github.com/datastructures-js/graph/blob/877f7e409186fd14721a392e911fe703d6c80947/src/directedGraph.js#L210), e.g. by letting the callback function return `false`.
Alternatively, a function for retrieving the vertices/edges of a given vertex would be very helpful, 
e.g. `getConnectedVertices`; `getConnectedEdges`

**Comment by eyas-ranjous** [comment]
@strarsis v5.3.0 released

### getConnectedVertices
https://github.com/datastructures-js/graph#getconnectedvertices

### getConnectedEdges
https://github.com/datastructures-js/graph#getconnectededges

### getVertexValue
https://github.com/datastructures-js/graph#getvertexvalue

### abort traversal
DFS https://github.com/datastructures-js/graph#traversedfs
BFS https://github.com/datastructures-js/graph#traversebfs
